[package]
name = "oxidizer-entity-macro"
version = "0.1.0"
authors = ["Gustavo Sampaio <gbritosampaio@gmail.com>", "davysson <davysson>"]
edition = "2018"
keywords = ["orm", "tokio-postgres", "refinery", "postgres", "sql", "entity"]
categories = ["database"]
repository = "https://github.com/oxidizer-rs/oxidizer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.18"
darling = "0.10.2"
async-trait = "0.1.31"
Inflector = "0.11.4"